### ISSUE TITLE
Upgrade nose to V2

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-france#1131]
Supersedes #1061

En gros, cette config :

```
; setup.cfg

[nosetests]
; cette ligne
where = tests
exe = true
with-doctest = true
```

crée des erreurs bizarres quand l'on utilise avec Python 3.x :

```
# openfisca-run-test $(circleci tests glob "tests/**/*.{yaml,yml}" | circleci tests split)
# circleci tests glob "tests/**/*.py" | circleci tests split | nosetests
E
======================================================================
ERROR: test suite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/venv/openfisca_france/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/tmp/venv/openfisca_france/lib/python3.6/site-packages/nose/suite.py", line 271, in setUp
    if not self:
  File "/tmp/venv/openfisca_france/lib/python3.6/site-packages/nose/suite.py", line 86, in __bool__
    test = next(self.test_generator)
  File "/tmp/venv/openfisca_france/lib/python3.6/site-packages/openfisca_core/tools/test_runner.py", line 84, in generate_tests
    for test in _generate_tests_from_file(tax_benefit_system, path, options):
  File "/tmp/venv/openfisca_france/lib/python3.6/site-packages/openfisca_core/tools/test_runner.py", line 136, in _generate_tests_from_file
    for test_index, (path_to_file, name, period_str, test) in enumerate(tests, 1):
  File "/tmp/venv/openfisca_france/lib/python3.6/site-packages/openfisca_core/tools/test_runner.py", line 175, in _parse_test_file
    with open(yaml_path) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/project/tests/tests/allegement_fillon.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
Exited with code 1
```

**Comment by Morendil** [comment]
J'ai modifié le titre car je ne pense pas qu'une montée de version soit un objectif en soi, peut-être un moyen mais ce n'est pas certain.

Par ailleurs je ne sais pas si cette issue a une forte valeur ajoutée, à défaut de résolution ou d'avancées dans les jours qui viennent je suis tenté de simplement fermer.
