### ISSUE TITLE
Erreur lors d'une conversion entier vers flottant

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#1197]
Le payload suivant

```json
{
    "individus": {
        "_": {
            "frais_reels": {
                "2018-01": 10000000000000000000
            },
            "revenu_assimile_salaire_apres_abattements": {
                "2018-01": null
            }
        }
    },
    "familles": {
        "_": {
            "parents": [
                "_"
            ]
        }
    },
    "foyers_fiscaux": {
        "_": {
            "declarants": [
                "_"
            ]
        }
    },
    "menages": {
        "_": {
            "personne_de_reference": [
                "_"
            ]
        }
    }
}
```

génère
```json
{
  "error": "Internal server error: Python int too large to convert to C long"
}
```

avec `curl -X POST https://openfisca.mes-aides.gouv.fr/calculate -d @data.json -H 'Content-Type: application/json'`

Serait-il possible de supprimer cette erreur ou au moins avoir un message plus _variable spécifique_ et intelligible pour les usagers finaux ?

Merci beaucoup.

**Comment by Morendil** [comment]
Potentiellement toutes les variables déclarées `int` ont le même problème alors.

Je serais tenté de dire "on change la variable en float" mais je vais tagger @fpagnoux - il y a peut-être des raisons de performance à ce choix ?

**Comment by Morendil** [comment]
Récurrence de cette issue de Core: https://github.com/openfisca/openfisca-core/issues/463

**Comment by Morendil** [comment]
La trace correspondante:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/openfisca-core/openfisca_web_api/app.py", line 142, in calculate
    result = handlers.calculate(tax_benefit_system, input_data)
  File "/app/openfisca-core/openfisca_web_api/handlers.py", line 15, in calculate
    simulation = Simulation(tax_benefit_system = tax_benefit_system, simulation_json = input_data)
  File "/app/openfisca-core/openfisca_core/simulations.py", line 83, in __init__
    self.instantiate_entities(simulation_json)
  File "/app/openfisca-core/openfisca_core/simulations.py", line 108, in instantiate_entities
    self.persons = self.tax_benefit_system.person_entity(self, persons_json)
  File "/app/openfisca-core/openfisca_core/entities.py", line 39, in __init__
    self.init_from_json(entities_json)
  File "/app/openfisca-core/openfisca_core/entities.py", line 64, in init_from_json
    self.init_variable_values(variables_json, entity_id)
  File "/app/openfisca-core/openfisca_core/entities.py", line 105, in init_variable_values
    array[entity_index] = value
OverflowError: Python int too large to convert to C long
```

**Comment by Morendil** [comment]
> Le problème provient du fait que frais_reels est un int 

Je confirme :)

> et qu'il apparait dans des calculs avec des float.

Le problème ne semble pas être là, mais plutôt venir de ce que `int` pour OpenFisca est, comme le signale @benjello, en réalité un `int32`. Ce n'est pas un souci de précision mais éventuellement d'élargissement (à int64). L'erreur que tu constates correspond à:

```
a = np.array([1],dtype='>i4')
>>> a
array([1], dtype=int32)
>>> a[0] = 10000000000000000000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```

Je corrige avec un message plus explicite.

**Comment by Morendil** [comment]
Je ferme, l'issue étant plus appropriée sur Core.
