### ISSUE TITLE
Dev install raises importlib_metadata dependency error

### ISSUE THREAD

**Issue by pzuldp** [openfisca/openfisca-france#2071]
Hello hello !

Je suis le fan numéro un d'OpenFisca, mais je viens de rencontrer un problème.

### Qu'ai-je fait ?

Après avoir installé OpenfiscaFrance sur une nouvelle machine (Windows) en mode développement, grâce à `pip install -e .`, j'ai essayé de runner les tests grâce à `openfisca test tests/`

### À quoi m'attendais-je ?

A une exécution sans erreur.

### Que s'est-il passé en réalité ?

La première tentative d'exécution des tests signale que le package `importlib_metadata` est manquant. Après l'avoir installé manuellement (`pip install importlib_metadata`), la même commande s'exécute sans problème (= tous les tests s'exécutent et passent avec succès).

### Voici des informations qui peuvent aider à reproduire le problème :

cf. commentaires ci-dessous

### Contexte

Je m'identifie plus en tant que :

- [x] Contributeur·e : je contribue à OpenFisca France.
- [ ] Développeur·e : je crée des outils qui utilisent OpenFisca France.
- [x] Économiste : je réalise des simulations avec des données.
- [ ] Mainteneur·e : j'intègre les contributions à OpenFisca France.
- [ ] Autre : _(ajoutez une description du contexte dans lequel vous utilisez OpenFisca)_.

**Comment by pzuldp** [comment]
`p.dutronc@pse-ipp-318-2 MINGW64 ~/Documents/research/projets/openfisca-france (master)
$ conda create -n openfisca_france python=3.8
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 23.1.0
  latest version: 23.3.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.3.0



## Package Plan ##

  environment location: C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-67.6.1          |     pyhd8ed1ab_0         567 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         567 KB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.12.7-h5b45459_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libsqlite          conda-forge/win-64::libsqlite-3.40.0-hcfcfb64_0
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4
  openssl            conda-forge/win-64::openssl-3.1.0-hcfcfb64_0
  pip                conda-forge/noarch::pip-23.0.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.8.16-h4de0772_1_cpython
  setuptools         conda-forge/noarch::setuptools-67.6.1-pyhd8ed1ab_0
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.3-hb6edc58_10
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_10
  wheel              conda-forge/noarch::wheel-0.40.0-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate openfisca_france
#
# To deactivate an active environment, use
#
#     $ conda deactivate


p.dutronc@pse-ipp-318-2 MINGW64 ~/Documents/research/projets/openfisca-france (master)
$ conda activate openfisca_france
(openfisca_france)
p.dutronc@pse-ipp-318-2 MINGW64 ~/Documents/research/projets/openfisca-france (master)
$ pip install -e .
Obtaining file:///C:/Users/p.dutronc/Documents/research/projets/openfisca-france
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting OpenFisca-Core<36.0,>=35.8.0
  Using cached OpenFisca_Core-35.12.0-py3-none-any.whl (211 kB)
Collecting PyYAML>=3.10
  Downloading PyYAML-6.0-cp38-cp38-win_amd64.whl (155 kB)
     ------------------------------------ 155.4/155.4 kB 772.3 kB/s eta 0:00:00
Collecting typing-extensions<5.0.0,>=4.0.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting psutil<6.0.0,>=5.4.7
  Downloading psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
     ------------------------------------- 252.5/252.5 kB 15.1 MB/s eta 0:00:00
Requirement already satisfied: pytest<6.0.0,>=4.4.1 in c:\users\p.dutronc\appdata\roaming\python\python38\site-packages (from OpenFisca-Core<36.0,>=35.8.0->OpenFisca-France==145.0.0) (5.4.3)
Requirement already satisfied: numexpr<=3.0,>=2.7.0 in c:\users\p.dutronc\appdata\roaming\python\python38\site-packages (from OpenFisca-Core<36.0,>=35.8.0->OpenFisca-France==145.0.0) (2.7.1)
Collecting numpy<1.21,>=1.11
  Using cached numpy-1.20.3-cp38-cp38-win_amd64.whl (13.7 MB)
Collecting sortedcontainers==2.2.2
  Using cached sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: dpath<3.0.0,>=1.5.0 in c:\users\p.dutronc\appdata\roaming\python\python38\site-packages (from OpenFisca-Core<36.0,>=35.8.0->OpenFisca-France==145.0.0) (1.5.0)
Collecting nptyping==1.4.4
  Using cached nptyping-1.4.4-py3-none-any.whl (31 kB)
Collecting typish>=1.7.0
  Using cached typish-1.9.3-py3-none-any.whl (45 kB)
Collecting attrs>=17.4.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ---------------------------------------- 60.0/60.0 kB ? eta 0:00:00
Requirement already satisfied: more-itertools>=4.0.0 in c:\users\p.dutronc\appdata\roaming\python\python38\site-packages (from pytest<6.0.0,>=4.4.1->OpenFisca-Core<36.0,>=35.8.0->OpenFisca-France==145.0.0) (8.4.0)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.1.tar.gz (14 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: py>=1.5.0 in c:\users\p.dutronc\appdata\roaming\python\python38\site-packages (from pytest<6.0.0,>=4.4.1->OpenFisca-Core<36.0,>=35.8.0->OpenFisca-France==145.0.0) (1.9.0)
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting packaging
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     ---------------------------------------- 42.7/42.7 kB ? eta 0:00:00
Building wheels for collected packages: atomicwrites
  Building wheel for atomicwrites (setup.py): started
  Building wheel for atomicwrites (setup.py): finished with status 'done'
  Created wheel for atomicwrites: filename=atomicwrites-1.4.1-py2.py3-none-any.whl size=6974 sha256=eb650ba10acd08d5bad3ba5191685b4a8a5a630d608f64ddacedb362964c27da
  Stored in directory: c:\users\p.dutronc\appdata\local\pip\cache\wheels\ce\24\c1\56b1ca77dda9577b75eb88d7ec50425f103ec2f6170c6e97df
Successfully built atomicwrites
Installing collected packages: wcwidth, typish, sortedcontainers, typing-extensions, PyYAML, psutil, pluggy, packaging, numpy, colorama, attrs, atomicwrites, nptyping, OpenFisca-Core, OpenFisca-France
  Running setup.py develop for OpenFisca-France
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas 1.0.5 requires python-dateutil>=2.6.1, which is not installed.
pandas 1.0.5 requires pytz>=2017.2, which is not installed.
Successfully installed OpenFisca-Core-35.12.0 OpenFisca-France PyYAML-6.0 atomicwrites-1.4.1 attrs-22.2.0 colorama-0.4.6 nptyping-1.4.4 numpy-1.20.3 packaging-23.0 pluggy-0.13.1 psutil-5.9.4 sortedcontainers-2.2.2 typing-extensions-4.5.0 typish-1.9.3 wcwidth-0.2.6
(openfisca_france)
p.dutronc@pse-ipp-318-2 MINGW64 ~/Documents/research/projets/openfisca-france (master)
$ openfisca test tests
Traceback (most recent call last):
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\scripts\__init__.py", line 59, in detect_country_package
    module = importlib.import_module(module_name)
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\p.dutronc\documents\research\projets\openfisca-france\openfisca_france\__init__.py", line 1, in <module>
    from openfisca_france.france_taxbenefitsystem import FranceTaxBenefitSystem
  File "c:\users\p.dutronc\documents\research\projets\openfisca-france\openfisca_france\france_taxbenefitsystem.py", line 3, in <module>
    from openfisca_core.taxbenefitsystems import TaxBenefitSystem
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\taxbenefitsystems\__init__.py", line 26, in <module>
    from .tax_benefit_system import TaxBenefitSystem  # noqa: F401
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\taxbenefitsystems\tax_benefit_system.py", line 9, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\Scripts\openfisca.exe\__main__.py", line 7, in <module>
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\scripts\openfisca_command.py", line 70, in main
    return sys.exit(main(parser))
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\scripts\run_test.py", line 15, in main
    tax_benefit_system = build_tax_benefit_system(args.country_package, args.extensions, args.reforms)
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\scripts\__init__.py", line 22, in build_tax_benefit_system
    country_package_name = detect_country_package()
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\scripts\__init__.py", line 64, in detect_country_package
    raise ImportError(message)
ImportError: Traceback (most recent call last):
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\scripts\__init__.py", line 59, in detect_country_package
    module = importlib.import_module(module_name)
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\p.dutronc\documents\research\projets\openfisca-france\openfisca_france\__init__.py", line 1, in <module>
    from openfisca_france.france_taxbenefitsystem import FranceTaxBenefitSystem
  File "c:\users\p.dutronc\documents\research\projets\openfisca-france\openfisca_france\france_taxbenefitsystem.py", line 3, in <module>
    from openfisca_core.taxbenefitsystems import TaxBenefitSystem
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\taxbenefitsystems\__init__.py", line 26, in <module>
    from .tax_benefit_system import TaxBenefitSystem  # noqa: F401
  File "C:\Users\p.dutronc\AppData\Local\anaconda3\envs\openfisca_france\lib\site-packages\openfisca_core\taxbenefitsystems\tax_benefit_system.py", line 9, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'

Could not import module `openfisca_france`.
Look at the stack trace above to determine the error that stopped installed modules detection.
(openfisca_france)
`

**Comment by pzuldp** [comment]
@benjello je te tagge parce que je t'en ai parlé, je ne sais pas trop qui ça peut intéresser d'autre

**Comment by pzuldp** [comment]
oh mais mon pb perso est réglé (je ne réinstalle pas openfisca tous les jours...), je signalais ce bug juste par acquis de conscience

**Comment by benjello** [comment]
Donc je ferme @pzuldp.
