### ISSUE TITLE
Erreur test apprenti

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-france#413]
Il semblerait que la version actuelle du code ne passe pas le test fiche_de_paie/apprenti.yaml.
Je suis en train de regarder pourquoi. Pour l'instant je vois que la remuneration_apprenti retourne anormalement 0...

**Comment by laem** [comment]
Looks like it's due to numpy 1.10...

**Comment by benjello** [comment]
Where is that ? The problems usually arise with datetime stuff.

**Comment by laem** [comment]
Yep, 
I replaced 
```python
(anciennete_contrat[age_condition] == anciennete) * part_de_smic
```
with
```python
(anciennete_contrat[age_condition] == np.array([anciennete], dtype = 'timedelta64[Y]')) * part_de_smic
```

**Comment by benjello** [comment]
Good job. Strange we did not see that with @cbenz.

**Comment by laem** [comment]
See #414

**Comment by cbenz** [comment]
> Good job. Strange we did not see that with @cbenz.

We relied only on tests. That's strange: after merging `aide-embauche` in `master` [travis is OK](https://travis-ci.org/openfisca/openfisca-france/builds/103598901) but on my machine:

```
~/D/o/openfisca-france (master|✔) $ nosetests --stop openfisca_france/tests/test_yaml.py
F
======================================================================
FAIL: openfisca_france.tests.test_yaml.test('/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/fiches_de_paie/apprenti.yaml', 'Apprenti petite entreprise', u'2015-03', {'output_variables': OrderedDict([('salaire_super_brut', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('remboursement_transport', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('ags', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-2.1400001], dtype=float32)}), ('agff_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-8.56999969], dtype=float32)}), ('agirc_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('agirc_gmp_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('apec_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('arrco_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-33.20999908], dtype=float32)}), ('chomage_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-28.56999969], dtype=float32)}), ('cotisation_exceptionnelle_temporaire_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('vieillesse_deplafonnee_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-12.85999966], dtype=float32)}), ('vieillesse_plafonnee_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-60.70999908], dtype=float32)}), ('fonds_emploi_hospitalier', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('ircantec_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('pension_civile_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('rafp_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('allocations_temporaires_invalidite', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('accident_du_travail', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-10.71000004], dtype=float32)}), ('famille', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-37.49000168], dtype=float32)}), ('mmid_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-91.41999817], dtype=float32)}), ('taxe_salaires', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('conge_individuel_formation_cdd', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('contribution_developpement_apprentissage', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('contribution_solidarite_autonomie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-2.1400001], dtype=float32)}), ('contribution_supplementaire_apprentissage', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('financement_organisations_syndicales', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-0.11], dtype=float32)}), ('formation_professionnelle', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-3.93000007], dtype=float32)}), ('fnal', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-0.70999998], dtype=float32)}), ('participation_effort_construction', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-3.21000004], dtype=float32)}), ('prevoyance_obligatoire_cadre', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('taxe_apprentissage', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('versement_transport', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('allegement_fillon', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('credit_impot_competitivite_emploi', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 42.84999847], dtype=float32)}), ('forfait_social', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('tehr', OrderedDict([(Period((u'year', Instant((2014, 1, 1)), 1)), array([ 0.], dtype=float32))])), ('assiette_cotisations_sociales', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 714.1831665], dtype=float32)}), ('cotisations_employeur', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-295.77999878], dtype=float32)}), ('exoneration_cotisations_employeur_apprenti', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 285.07000732], dtype=float32)}), ('cotisations_salariales', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('cotisations_salariales_contributives', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-96.05000305], dtype=float32)}), ('cotisations_salariales_non_contributives', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-5.36000013], dtype=float32)}), ('exoneration_cotisations_salariales_apprenti', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 101.41000366], dtype=float32)}), ('agff_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-5.71000004], dtype=float32)}), ('agirc_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('agirc_gmp_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('apec_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('arrco_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-22.13999939], dtype=float32)}), ('chomage_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-17.13999939], dtype=float32)}), ('cotisation_exceptionnelle_temporaire_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('vieillesse_deplafonnee_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-2.1400001], dtype=float32)}), ('vieillesse_plafonnee_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-48.91999817], dtype=float32)}), ('ircantec_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('pension_civile_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('rafp_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('mmid_salarie', {Period((u'month', Instant((2015, 3, 1)), 1)): array([-5.36000013], dtype=float32)}), ('csg_deductible_salaire', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('mhsup', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('csg_imposable_salaire', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('crds_salaire', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('hsup', {Period((u'month', Instant((2015, 3, 1)), 1)): array([0], dtype=int32)}), ('depense_cantine_titre_restaurant_employe', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 0.], dtype=float32)}), ('salaire_net_a_payer', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 714.1831665], dtype=float32)}), ('apprenti', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ True], dtype=bool)}), ('remuneration_apprenti', {Period((u'month', Instant((2015, 3, 1)), 1)): array([ 714.1831665], dtype=float32)})]), 'output_variables_name_to_ignore': set(['salaire_super_brut']), 'absolute_error_margin': 0.005, 'name': 'Apprenti petite entreprise', 'scenario': <openfisca_france.scenarios.Scenario object at 0x7f24278d81d0>}, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/test_yaml.py", line 160, in check
    relative_error_margin = test.get('relative_error_margin'),
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/tools.py", line 38, in assert_near
    abs(target_value - value), absolute_error_margin)
AssertionError: ags@2015-03: [ 0.] differs from [-2.1400001] with an absolute margin [ 2.1400001] > 0.005
-------------------- >> begin captured logging << --------------------
openfisca_france.tests.test_yaml: INFO: Ignoring /home/cbenz/Dev/openfisca/openfisca-france/openfisca_france/tests/calculateur_impots
openfisca_core.formulas: INFO: <=> age@individus<2015-03>(birth@individus<2015-03>[1996-01-01]) --> <2015-03>[19]
openfisca_core.formulas: INFO: <=> apprenti@individus<2015-03>(age@individus<2015-03>[19], apprentissage_contrat_debut@individus<2015-03>[2013-01-01]) --> <2015-03>[True]
openfisca_core.formulas: INFO: <=> indemnite_residence@individus<2015-03>(traitement_indiciaire_brut@individus<2015-03>[0.0], salaire_de_base@individus<2015-03>[0.0], type_sal@individus<2015-03>[0], zone_apl_individu@individus<2015-03>[2]) --> <2015-03>[0.0]
openfisca_core.formulas: INFO: <=> remuneration_apprenti@individus<2015-03>(age@individus<2015-03>[19], apprentissage_contrat_debut@individus<2015-03>[2013-01-01], apprenti@individus<2015-03>[True]) --> <2015-03>[0.0]
openfisca_core.formulas: INFO: <=> smic_proratise@individus<2015-03>(coefficient_proratisation@individus<2015-03>[1.0]) --> <2015-03>[1457.52]
openfisca_core.formulas: INFO: <=> assiette_cotisations_sociales_prive@individus<2015-03>(apprenti@individus<2015-03>[True], avantage_en_nature@individus<2015-03>[0.0], hsup@individus<2015-03>[0], indemnites_compensatrices_conges_payes@individus<2015-03>[0.0], indemnite_residence@individus<2015-03>[0.0], primes_fonction_publique@individus<2015-03>[0.0], primes_salaires@individus<2015-03>[0.0], reintegration_titre_restaurant_employeur@individus<2015-03>[0.0], remuneration_apprenti@individus<2015-03>[0.0], salaire_de_base@individus<2015-03>[0.0], type_sal@individus<2015-03>[0], smic_proratise@individus<2015-03>[1457.52]) --> <2015-03>[0.0]
openfisca_core.formulas: INFO: <=> plafond_securite_sociale@individus<2015-03>(heures_non_remunerees_volume@individus<2015-03>[0.0], nombre_jours_calendaires@individus<2015-03>[31.0]) --> <2015-03>[3170.0]
openfisca_core.formulas: INFO: <=> ags@individus<2015-03>(cotisation_sociale_mode_recouvrement@individus<2015-03>[0], assiette_cotisations_sociales@individus<2015-03>[0.0], plafond_securite_sociale@individus<2015-03>[3170.0], type_sal@individus<2015-03>[0]) --> <2015-03>[0.0]
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.192s

FAILED (failures=1)

```

**Comment by cbenz** [comment]
In the [Travis build raw log](https://api.travis-ci.org/jobs/103598902/log.txt?deansi=true) we see:

```
Setting up python-numpy (1:1.6.1-6ubuntu1) ...
```

(and not 1.10)

Travis relies on Ubuntu Precise, and in this version Python is 1.6: [proof](http://packages.ubuntu.com/fr/precise/python-numpy)

**Comment by laem** [comment]
:+1:

**Comment by benjello** [comment]
:+1:

**Comment by cbenz** [comment]
Let's continue on https://github.com/openfisca/openfisca-france/issues/416
