### ISSUE TITLE
API installation fails

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france#765]
In Mes-Aides-UI, I wanted to depend on `openfisca_france[api]` to delegate synchronous version  upgrades of `openfisca_web_api` to `openfisca_france`.

I [tried that](https://circleci.com/gh/sgmap/mes-aides-ui/1725#artifacts/containers/0) and got [an error](https://1725-18399519-gh.circle-artifacts.com/0/tmp/circle-artifacts.w2gX7dm/stderr_npm_16211.txt) because `OpenFisca-Parsers` was not installed.

I tried to [update openfisca_france[api]](https://circleci.com/gh/sgmap/mes-aides-ui/1729) to require `OpenFisca-Core[parser]` but that failed too.

I finally [indicated `OpenFisca-Parsers >= 1.0.2, < 2.0`](https://github.com/guillett/openfisca-france/commit/b76c64e83d1803f16756268737934065f1045e54) as an explicit dependency of `openfisca_france[api]` and [that worked](https://circleci.com/gh/sgmap/mes-aides-ui/1730).

It is not completely satisfying as that requirement needs to be kept in sync between OpenFisca-Core and OpenFisca-France but it makes things easier for new-comers.

I've also done the following experiment on a brand new virtualenv and OpenFisca-Parsers does not get installed.
That doesn't seem to be an issue with `openfisca-serve` but seems to lead to my issue when the API is served via `gunicorn`.

I can open a PR with my hack but I just wanted to start a conversation.

```shell
Last login: Fri May 26 15:28:50 on ttys002
➜  mes-aides-ui git:(bump_op18) ✗ viruta
➜  mes-aides-ui git:(bump_op18) ✗ virtualenv  --python=python2 /tmp/testVE
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /tmp/testVE/bin/python2.7
Also creating executable in /tmp/testVE/bin/python
Installing setuptools, pip, wheel...source /tmp/testVE/bin/done.
➜  mes-aides-ui git:(bump_op18) ✗ source /tmp/testVE/bin/activate
(testVE) ➜  mes-aides-ui git:(bump_op18) ✗ pip install --upgrade pip
Requirement already up-to-date: pip in /private/tmp/testVE/lib/python2.7/site-packages
(testVE) ➜  mes-aides-ui git:(bump_op18) ✗ pip install openfisca_france[api]
Collecting openfisca_france[api]
  Using cached OpenFisca_France-18.2.6-py2-none-any.whl
Collecting numpy>=1.11 (from openfisca_france[api])
  Using cached numpy-1.12.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting PyYAML>=3.10 (from openfisca_france[api])
Collecting OpenFisca-Core<13.0,>=12.1.1 (from openfisca_france[api])
  Using cached OpenFisca_Core-12.1.4-py2-none-any.whl
Collecting requests>=2.8 (from openfisca_france[api])
  Using cached requests-2.14.2-py2.py3-none-any.whl
Collecting Biryani[datetimeconv]>=0.10.4 (from openfisca_france[api])
  Using cached Biryani-0.10.4-py2-none-any.whl
Collecting OpenFisca-Web-API<6.0,>=4.0.0; extra == "api" (from openfisca_france[api])
  Using cached OpenFisca_Web_API-5.1.0-py2-none-any.whl
Collecting lxml>=3.7 (from OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
Collecting gunicorn>=19.7.1 (from OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl
Collecting flask-cors==3.0.2 (from OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
  Using cached Flask_Cors-3.0.2-py2.py3-none-any.whl
Collecting flask==0.12 (from OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
  Using cached Flask-0.12-py2.py3-none-any.whl
Collecting Babel>=0.9.4 (from Biryani[datetimeconv]>=0.10.4->openfisca_france[api])
  Using cached Babel-2.4.0-py2.py3-none-any.whl
Collecting isodate>=0.4; extra == "datetimeconv" (from Biryani[datetimeconv]>=0.10.4->openfisca_france[api])
Collecting pytz; extra == "datetimeconv" (from Biryani[datetimeconv]>=0.10.4->openfisca_france[api])
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting PasteDeploy (from OpenFisca-Web-API<6.0,>=4.0.0; extra == "api"->openfisca_france[api])
  Using cached PasteDeploy-1.5.2-py2.py3-none-any.whl
Collecting WebOb>=1.1 (from OpenFisca-Web-API<6.0,>=4.0.0; extra == "api"->openfisca_france[api])
  Using cached WebOb-1.7.2-py2.py3-none-any.whl
Collecting WebError>=0.10 (from OpenFisca-Web-API<6.0,>=4.0.0; extra == "api"->openfisca_france[api])
  Using cached WebError-0.13.1-py2-none-any.whl
Requirement already satisfied: Six in /private/tmp/testVE/lib/python2.7/site-packages (from flask-cors==3.0.2->OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
Collecting Jinja2>=2.4 (from flask==0.12->OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask==0.12->OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting click>=2.0 (from flask==0.12->OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
  Using cached click-6.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.12->OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
Collecting Tempita (from WebError>=0.10->OpenFisca-Web-API<6.0,>=4.0.0; extra == "api"->openfisca_france[api])
Collecting Pygments (from WebError>=0.10->OpenFisca-Web-API<6.0,>=4.0.0; extra == "api"->openfisca_france[api])
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting Paste>=1.7.1 (from WebError>=0.10->OpenFisca-Web-API<6.0,>=4.0.0; extra == "api"->openfisca_france[api])
  Using cached Paste-2.0.3-py2-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->flask==0.12->OpenFisca-Core<13.0,>=12.1.1->openfisca_france[api])
Installing collected packages: numpy, PyYAML, lxml, pytz, Babel, isodate, Biryani, gunicorn, MarkupSafe, Jinja2, Werkzeug, click, itsdangerous, flask, flask-cors, OpenFisca-Core, requests, PasteDeploy, WebOb, Tempita, Pygments, Paste, WebError, OpenFisca-Web-API, openfisca-france
Successfully installed Babel-2.4.0 Biryani-0.10.4 Jinja2-2.9.6 MarkupSafe-1.0 OpenFisca-Core-12.1.4 OpenFisca-Web-API-5.1.0 Paste-2.0.3 PasteDeploy-1.5.2 PyYAML-3.12 Pygments-2.2.0 Tempita-0.5.2 WebError-0.13.1 WebOb-1.7.2 Werkzeug-0.12.2 click-6.7 flask-0.12 flask-cors-3.0.2 gunicorn-19.7.1 isodate-0.5.4 itsdangerous-0.24 lxml-3.7.3 numpy-1.12.1 openfisca-france-18.2.6 pytz-2017.2 requests-2.14.2
(testVE) ➜  mes-aides-ui git:(bump_op18) ✗ gunicorn
(testVE) ➜  mes-aides-ui git:(bump_op18) ✗ gunicorn --workers 1 --paster openfisca/api_config.ini
[2017-05-26 16:05:47 +0200] [8794] [INFO] Starting gunicorn 19.7.1
[2017-05-26 16:05:47 +0200] [8794] [INFO] Listening at: http://0.0.0.0:2000 (8794)
[2017-05-26 16:05:47 +0200] [8794] [INFO] Using worker: sync
[2017-05-26 16:05:47 +0200] [8797] [INFO] Booting worker with pid: 8797
[2017-05-26 16:05:47 +0200] [8797] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=self.cfg.paste_global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/gunicorn/app/pasterapp.py", line 69, in load_pasteapp
    global_conf=global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/Volumes/SSD-Home/thomas/Library/Python/2.7/lib/python/site-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (OpenFisca-Core 10.0.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('OpenFisca-Core[parsers]<9.0,>=8.0'), set(['OpenFisca-Web-API']))
[2017-05-26 16:05:48 +0200] [8797] [INFO] Worker exiting (pid: 8797)
[2017-05-26 16:05:48 +0200] [8794] [INFO] Shutting down: Master
[2017-05-26 16:05:48 +0200] [8794] [INFO] Reason: Worker failed to boot.
(testVE) ➜  mes-aides-ui git:(bump_op18) ✗
```

**Comment by MattiSG** [comment]
Merci d'avoir rapporté ce problème !

Nous travaillons en ce sens à intégrer directement l'API dans Core afin de ne pas multiplier les dépendances.

En l'occurence, @fpagnoux, s'agit-il du problème connu dans https://github.com/openfisca/openfisca-web-api/issues/106 ou d'un autre ?

**Comment by fpagnoux** [comment]
Je reproduis le problème, mais je ne suis pas sûr de comprendre d'où ça vient:
Les parsers sont [bien déclarés](https://github.com/openfisca/openfisca-web-api/blob/master/setup.py#L57) comme une dépendance de web-api (via une [dépendance optionnelle](https://github.com/openfisca/openfisca-core/blob/master/setup.py#L32) de core). Pourtant, ils ne s'installent pas. 

La solution la plus "simple" que je vois est de continuer à gérer dans mes-aides la cohérence entre la version de France et la version de la Web API. 

Le fix que tu proposes revient à faire de même en gérant la cohérence entre les parsers et france. Ça me paraît un peu moins bien dans la mesure où il est plus naturel pour mes-aides de demander l'installation d'une version spécifique d'une API, plutôt que de demander l'installation spécifique d'un package technique avec lequel il n'interagit pas.

Une fois de plus, le comportement de `pip` pose problème. Comme le dit @MattiSG, l'API preview est aujourd'hui incluse dans Core pour éviter la complexité de ces gestions de dépendances. Peut-être devrait-on considérer d'intégrer aussi à core les parsers et l'API legacy ?

**Comment by MattiSG** [comment]
@guillett peux-tu ouvrir une PR sur `openfisca-web-api` comme tu le suggérais ? 🙂 Même si cette API sera à terme dépréciée, il est important qu'elle fonctionne aujourd'hui, même si cela implique un coût de maintenance plus élevé en explicitant les dépendances.

**Comment by MattiSG** [comment]
Cela devrait être corrigé via https://github.com/openfisca/openfisca-core/issues/500. @guillett Si ce n'est pas le cas, merci d'ouvrir une nouvelle issue dans openfisca/openfisca-web-api en référençant celle-ci  😉
