### ISSUE TITLE
Rendre OpenFisca-France clonable sous Windows

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-france#819]
> Il semblerait qu'il soit impossible de cloner openfisca-france  sous windows depuis que la profondeur et les taille des noms de répertoire ont augmenté considérablement (paramètres YAML).

Problème reporté par @ClaireLeroyIPP et  @benjello 

Stack trace:

```
cleroy@IPP-WKS-15 MINGW64 ~/Documents/GitHub
$ pip install openfisca-france
Collecting openfisca-france
  Downloading OpenFisca_France-18.9.2-py2-none-any.whl (1.8MB)
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\python27\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 498, in unzip_file
    ensure_dir(dir)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 206] Nom de fichier ou extension trop long: 'c:\\users\\cleroy\\appdata\\local\\temp\\pip-build-zrgeah\\openfisca-france\\openfisca_france/parameters/impot_revenu/plus_values/imposition_des_plus_values_mobilieres_levees_d_options_attribuees_depuis_27_4_2000_cessions_realisees_moins_de_deux_ans_apres_la_levee'
```

**Comment by fpagnoux** [comment]
The bug seems to happen for a really long parameter name : `imposition_des_plus_values_mobilieres_levees_d_options_attribuees_depuis_27_4_2000_cessions_realisees_moins_de_deux_ans_apres_la_levee `.

Maybe renaming this parameter can solve the issue ?

**Comment by fpagnoux** [comment]
`git clone https://github.com/openfisca/openfisca-france.git` works on Windows ! @benjello @Claire Leroy do you confirm ?

**Comment by benjello** [comment]
@bfabre01 : tu as ce que tu voulais !

**Comment by bfabre01** [comment]
@fpagnoux : avec du retard, merci beaucoup ! Ça marche !
